const fs = require('fs');
const path = require('path');
const R = (p) => JSON.parse(fs.readFileSync(path.join(__dirname, p), 'utf8'));
const cov = R('coverage.json');
const enh = R('enhance/inputs.json'), tr = R('translate/inputs.json'), jar = R('jargonary/inputs.json');
// analyzer stats from the sibling corpus
let an = { docs: 10, patterns: 34, hidden: 12 };
try {
  const gt = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'corpus', 'ground-truth.json'), 'utf8'));
  const p = gt.documents.reduce((n, d) => n + d.planted.length, 0);
  an = { docs: gt.documents.length, patterns: p, hidden: gt.documents.reduce((n, d) => n + d.planted.filter((x) => x.category === 'hidden_terms_and_costs').length, 0) };
} catch {}

const L = [];
L.push('# ReVision — Four-Tool Batch Test & Evaluation');
L.push('');
L.push(`Generated ${cov.generated}. All inputs are fictional. This covers all four tools; the Fine Print Analyzer corpus lives in \`../corpus\`.`);
L.push('');
L.push('## Corpus at a glance');
L.push('');
L.push('| Tool | Inputs | Coverage | Output | Gradeable how |');
L.push('|---|---|---|---|---|');
L.push(`| Fine Print Analyzer | ${an.docs} | 5 categories, all subtypes | structured JSON | **exact** — vs ${an.patterns} ground-truth patterns |`);
L.push(`| Enhance | ${enh.inputs.length} | ${cov.tools.enhance.doc_types} doc types | plain text | rubric (${enh.rubric.length} checks) |`);
L.push(`| Translate | ${tr.inputs.length} | ${cov.tools.translate.target_langs.length} target langs, ${cov.tools.translate.source_langs_detected.length} detected sources | JSON | rubric (${tr.rubric.length} checks) |`);
L.push(`| Jargonary | ${jar.inputs.length} | ${cov.tools.jargonary.domains.length} domains, ${cov.tools.jargonary.levels.length} levels, ${cov.tools.jargonary.glossary_terms} terms | JSON | rubric (${jar.rubric.length} checks) |`);
L.push('');
L.push(`**Total: ${an.docs + enh.inputs.length + tr.inputs.length + jar.inputs.length} test inputs across the four tools.**`);
L.push('');
L.push('## Why the tools grade differently');
L.push('');
L.push('The Analyzer returns structured JSON, so it grades against exact ground truth (the 34 planted patterns). The other three are **generative** — no single correct output — so they grade against **machine-checkable rubric assertions** that hold regardless of wording:');
L.push('');
L.push('**Enhance** — ' + enh.rubric.join(', '));
L.push('');
L.push('**Translate** — ' + tr.rubric.join(', '));
L.push('');
L.push('**Jargonary** — ' + jar.rubric.join(', '));
L.push('');
L.push('These avoid the trap of scoring style: they check meaning-preservation (must-keep numbers/terms survive), structural validity (parseable JSON, non-empty fields), directional correctness (detected language, tone signal, glossary recall) — not prose quality.');
L.push('');
L.push('## What can be evaluated now vs. live');
L.push('');
L.push('- **Now (no key):** corpus completeness and balance — done. Every tool has ≥6 varied inputs with defined must-keep tokens and expected outcomes. The Analyzer’s static evaluation (coverage + the 35% hidden-terms finding) is in `../corpus/evaluation-report.md`.');
L.push('- **Live (needs a keyed session):** the rubric pass-rates. Each generative-tool input is scored by running it through the tool and applying the assertions above. Recall/pass-rate is only meaningful against real model output.');
L.push('');
L.push('## Running the live evaluation');
L.push('');
L.push('```bash');
L.push('ANTHROPIC_API_KEY=sk-ant-... revision &        # start server (fresh keyed session)');
L.push('node ../corpus/grade.js  http://localhost:8000  # Analyzer: recall + score bands');
L.push('node grade-tools.js      http://localhost:8000  # Enhance/Translate/Jargonary rubric pass-rates');
L.push('# or one tool: node grade-tools.js http://localhost:8000 jargonary');
L.push('```');
L.push('');
L.push('Each grader prints per-input pass/fail, per-check pass rates, and a clean-input count. LLM-as-judge scoring (nuanced quality) can be layered on later; the rubric layer is the objective floor.');
fs.writeFileSync(path.join(__dirname, 'evaluation-report.md'), L.join('\n') + '\n');
console.log('wrote evaluation-report.md');
console.log(`total inputs across 4 tools: ${an.docs + enh.inputs.length + tr.inputs.length + jar.inputs.length}`);
